### ISSUE TITLE
ValueError: multiple inheritance is not allowed with VTK classes

### ISSUE THREAD

**Issue by adessein** [akaszynski/vtkInterface#1]
I am using conda 4.3.25 on Windows, and I have created an environment for python 2.7 in order to be able to install vtk.
Then I have installed pyansys and vtkInterface using pip.
When trying to import pyansys i get

```
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pyansys
C:\Users\myusername\AppData\Local\Continuum\Anaconda3\envs\py27\lib\site-packages\pyansys\archive_reader.py:32: UserWarning: Unable to load vtk dependent modules
  warnings.warn('Unable to load vtk dependent modules')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\myusername\AppData\Local\Continuum\Anaconda3\envs\py27\lib\site-packages\pyansys\__init__.py", line 4, in <module>
    from pyansys.binary_reader import *
  File "C:\Users\myusername\AppData\Local\Continuum\Anaconda3\envs\py27\lib\site-packages\pyansys\binary_reader.py", line 7, in <module>
    import vtkInterface
  File "C:\Users\myusername\AppData\Local\Continuum\Anaconda3\envs\py27\lib\site-packages\vtkInterface\__init__.py", line 7, in <module>
    from vtkInterface.polydata import PolyData
  File "C:\Users\myusername\AppData\Local\Continuum\Anaconda3\envs\py27\lib\site-packages\vtkInterface\polydata.py", line 22, in <module>
    class PolyData(vtkPolyData, vtkInterface.Common):
ValueError: multiple inheritance is not allowed with VTK classes
```

Any clue on how to solve this ?

**Comment by akaszynski** [comment]
What’s your vtk version?

**Comment by adessein** [comment]
Thanks for reacting so quickly.
I have vtk 6.3.0 installed.

**Comment by akaszynski** [comment]
I’ll reproduce the error on my end and come up with a solution.

**Comment by akaszynski** [comment]
Turns out that VTK <7.0 doesn't support multiple inheritance.  I'll update the install requirements to reflect this in the next update.  You can install vtk 7.0 for python 2.7 using:
```
conda install -c menpo vtk 
```

VTK now supports pip using Python 3.6 when you're willing on taking the dive and switching over to Python 3.
https://pypi.python.org/pypi/vtk

Thanks for pointing out this bug!

**Comment by akaszynski** [comment]
Actually, you can get version 8.0.1 here:
```
conda install -c conda-forge vtk 
```

This is made by VTK, so I'd recommend using their package over the other ones.   It supports windows and python 2.7.
