### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by FIXDiz** [akaszynski/vtkInterface#8]
Hello i tried installing your package via pip (i'm running python 3.6.3 on anaconda) and got this error:
***********************************************************************************************************
`runfile('C:/Users/Tomas/Desktop/teste.py', wdir='C:/Users/Tomas/Desktop')
Traceback (most recent call last):

  File "<ipython-input-18-20c78685264f>", line 1, in <module>
    runfile('C:/Users/Tomas/Desktop/teste.py', wdir='C:/Users/Tomas/Desktop')

  File "C:\Users\Tomas\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\Tomas\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Tomas/Desktop/teste.py", line 1, in <module>
    import vtkInterface

  File "C:\Users\Tomas\Anaconda3\lib\site-packages\vtkInterface\__init__.py", line 10, in <module>
    from vtkInterface.plotting import *

  File "C:\Users\Tomas\Anaconda3\lib\site-packages\vtkInterface\plotting.py", line 12, in <module>
    from PIL import Image

  File "C:\Users\Tomas\Anaconda3\lib\site-packages\PIL\Image.py", line 56, in <module>
    from . import _imaging as core

ImportError: DLL load failed: The specified module could not be found.`
***********************************************************************************************************
Can't figure out why i'm getting this error, as i've vtk installed (vtk 8.1.0).
Can you help me out?

OS: Windows 10

**Comment by akaszynski** [comment]
Turns out that it's due to an old module requirement.  I've removed that and uploaded the new version to PyPi and here on GitHub.  Let me know if this solves the issue on your end.

**Comment by FIXDiz** [comment]
Works like a charm! Thanks man
